language: php
php: '7.1'

before_script:
  - composer install

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check

deploy:
  provider: heroku
  api_key:
    secure: "4915ac59-d9c7-486c-9f16-c443fc20fc5d"
  app: gasanovshamil
  on:
    repo: GasanovShamil/GasanovShamil.github.io
    branch: master
    php: '7.1'
notifications:
  email:
    recipients:
      - gasanov.sh@gmail.com
    on_success: never
    on_failure: always